#main page
team_erp_stores_dashboard:
    pattern:  /dashboard
    defaults: { _controller: TeamERPStoresBundle:Dashboard:dashboard }

#create new category    
team_erp_stores_new_category:
    pattern:  /new/category
    defaults: { _controller: TeamERPStoresBundle:Category:new }    
#Create measure units
team_erp_stores_new_measure_unit:
    pattern:  /new/measure/unit
    defaults: { _controller: TeamERPStoresBundle:Configuration:newMeasureUnit }
#Create new product
team_erp_stores_new_product:
    pattern:  /new/product
    defaults: { _controller: TeamERPStoresBundle:Product:new }
#Search product
team_erp_stores_search_product:
    pattern:  /search/product
    defaults: { _controller: TeamERPStoresBundle:Product:search }
#Add new quantity on hand
team_erp_stores_on_hand:
    pattern:  /on/hand
    defaults: { _controller: TeamERPStoresBundle:Product:onHand }    
#Receive products
team_erp_stores_invoice:
    pattern:  /new/invoice
    defaults: { _controller: TeamERPStoresBundle:Invoice:new }    
#Receive products
team_erp_stores_list_invoice:
    pattern:  /list/invoice
    defaults: { _controller: TeamERPStoresBundle:Invoice:list }
#issue job orders
team_erp_stores_issue_order:
    pattern:  /new/issue
    defaults: { _controller: TeamERPStoresBundle:Issue:new }    
team_erp_stores_list_issue:
    pattern:  /list/issue
    defaults: { _controller: TeamERPStoresBundle:Issue:list }
#Edit category
team_erp_stores_edit_category:
    pattern: /edit/category/{id}
    defaults: { _controller: TeamERPStoresBundle:Category:edit }
#Delete category
team_erp_stores_remove_category:
    pattern: /remove/category/{id}
    defaults: { _controller: TeamERPStoresBundle:Category:remove }
