parameters:
#    team_erp_stores.example.class: TeamERP\StoresBundle\Example

services:
#    team_erp_stores.example:
#        class: %team_erp_stores.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    teamerp.menu_builder_stores:
        class: TeamERP\StoresBundle\Menu\BuilderLeftSideBarStores
        arguments: ["@knp_menu.factory", "@security.context"]
        
    teamerp.menu.leftsidebarstores:
        class: Knp\Menu\MenuItem
        factory_service: teamerp.menu_builder_stores
        factory_method: leftSideBarStores
        arguments: ["@request"]
        scope: request 
        tags:
            - { name: knp_menu.menu, alias: side_left_stores }
            
    teamerp.controller.category_new:
        class: TeamERP\StoresBundle\Controller\CategoryController
        arguments: [@request=]
        tags:
            - { name: controller.category, alias: new_category }
    
    teamerp_stores.form.type.category:
        class: TeamERP\StoresBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: category }            