parameters:
#    team_erp_transport.example.class: TeamERP\TransportBundle\Example

services:
#    team_erp_transport.example:
#        class: %team_erp_transport.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
