parameters:
#    team_erp_transport.example.class: TeamERP\TransportBundle\Example

services:
    #category form
    teamerp_stores.form.type.category:
        class: TeamERP\StoresBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: category }

 

