parameters:
#    team_erp_user.example.class: TeamERP\UserBundle\Example

services:
#    team_erp_user.example:
#        class: %team_erp_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    teamerp_user.registration.form.type:
        class: TeamERP\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: teamerp_user_registration }
            
    teamerp_user.profile_edit.form.type:
        class: TeamERP\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: teamerp_user_profile_edit }       
            
    teamerp.menu_builder_admin:
        class: TeamERP\UserBundle\Menu\BuilderAdminLetfSideBar
        arguments: ["@knp_menu.factory", "@security.context"]  
        
    teamerp_user.menu.adminleftsidebar:
        class: Knp\Menu\MenuItem
        factory_service: teamerp.menu_builder_admin
        factory_method: adminLeftSideBar
        arguments: ["@request"]
        scope: request 
        tags:
            - { name: knp_menu.menu, alias: admin_side_left }           