parameters:
#    team_erp_user.example.class: TeamERP\UserBundle\Example

services:
#    team_erp_user.example:
#        class: %team_erp_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    teamerp_user.registration.form.type:
        class: TeamERP\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: teamerp_user_registration }