parameters:
services:    
    teamerp_customer.form.type.customer:
        class: TeamERP\CustomerBundle\Form\Type\CustomerType
        tags:
            - { name: form.type, alias: customer } 
    teamerp_customer.type.issue_selector:
        class: TeamERP\CustomerBundle\Form\Type\CompanySelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
        - { name: form.type, alias: company_selector }     
    
    teamerp.menu_builder:
        class: TeamERP\CustomerBundle\Menu\BuilderSalesLetfSideBar
        arguments: ["@knp_menu.factory", "@security.context"]  
        
    teamerp_sales.menu.salesleftsidebar:
        class: Knp\Menu\MenuItem
        factory_service: teamerp.menu_builder
        factory_method: SalesleftSideBar
        arguments: ["@request"]
        scope: request 
        tags:
            - { name: knp_menu.menu, alias: sales_side_left }
        