<?php

namespace TeamERP\TransportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuelPurchaseRepository extends EntityRepository
{
    public function findByCriteria ($invoice)
    {
        $dql = "SELECT f FROM TeamERPTransportBundle:FuelPurchase f
                WHERE f.invoice LIKE :invoice";
        return $this->getEntityManager()
            ->createQuery($dql)
                ->setParameter('invoice', '%'.$invoice.'%')
                ->getResult();
    }
}
