parameters:
#    team_erp_base.example.class: TeamERP\BaseBundle\Example

services:
    teamerp.menu_builder:
        class: TeamERP\BaseBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@security.context"]
#        arguments: ["@security.context"]
    teamerp.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: teamerp.menu_builder
        factory_method: mainMenu
        arguments: ["@request"]
        scope: request 
        tags:
            - { name: knp_menu.menu, alias: main }
            
    kernel.listener.teamerp_base_exception_listener:
        class: TeamERP\BaseBundle\Listener\ExceptionListener
        arguments: [@templating, @kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, alias: exception_listener }            